apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: obj-oct7-fb-1 
  description: Secure Supply Chain Example for Object Detection Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=obj-oct7-fb-1  
    janus-idp.io/tekton: obj-oct7-fb-1 
    backstage.io/kubernetes-id: obj-oct7-fb-1 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: maysunfaisal/obj-oct7-fb-1
  tags: ["ai", "detr", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 